# Generated by Django 5.2.3 on 2025-06-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_education_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Percentage value (0-100)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which skills appear')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
